# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm build
  displayName: 'Build'
  env:
    API_BASE_URI: $(API_BASE_URI)

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'onlineteamscan_v2_fe/dist/*'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(2)(ebf7d75f-9375-42c6-95d8-9916ad4854ac)'
    Destination: 'AzureBlob'
    storage: 'onlineteamscanapp'
    ContainerName: '$web'
