# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'
  workingDirectory: 'onlineteamscan_v2_fe/'

- script: |
    NUXT_ENV_STAGE=true & npm run build
  displayName: 'Build'
  workingDirectory: 'onlineteamscan_v2_fe/'
  env:
    API_BASE_URI: $(API_BASE_URI)

- task: CopyFiles@2
  displayName: 'Copy files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      .nuxt/**
      
      static/**
      
      package.json
      
      nuxt.config.js

      web.config
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
    replaceExistingArchive: true
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(10)(ebf7d75f-9375-42c6-95d8-9916ad4854ac)'
    appType: 'webApp'
    WebAppName: 'euricom-stage-teamscan-frontend'
    deployToSlotOrASE: true
    ResourceGroupName: 'stage-teamscan'
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/package.zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(12)(ebf7d75f-9375-42c6-95d8-9916ad4854ac)'
    appType: 'webApp'
    WebAppName: 'euricom-stage-teamscan-frontend'
    deployToSlotOrASE: true
    ResourceGroupName: 'stage-teamscan'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'   